services:
  web:
    build: .
    command: > 
      bash -c "npx prisma db push && npx prisma db seed && npm run start"
    ports:
      - "3030:3030"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./dist/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"