services:
  web:
    build: .
    command: > 
      bash -c "npx prisma db push && npx prisma db seed && npm run start"
    ports:
      - "3030:3030"
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./dist/data/redis:/data
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./dist/data/postgres:/var/lib/postgresql/data
